# Enable split keyboard support
CONFIG_ZMK_SPLIT=y

# Dongle needs to act as central and have 2 peripherals connect to it
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# You can theoretically add displays or extra rgb to dongle because battery
