# Name the keyboard
CONFIG_ZMK_KEYBOARD_NAME="Cygnus"

# Uncomment the following line to enable the cygnus OLED Display
# CONFIG_ZMK_DISPLAY=y

# --- SLEEP SETTINGS ---
CONFIG_ZMK_SLEEP=y
# Sleep after 10 minutes (600000 ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Enable ZMK Pointing
CONFIG_ZMK_POINTING=y
